CREATE TABLE LOG_AUDITORIA (
    ID_LOG_AUDITORIA BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TABLA VARCHAR(100) NOT NULL,
    ID_REGISTRO VARCHAR(100) NOT NULL,
    ACCION VARCHAR(50) NOT NULL,
    CAMPO_MODIFICADO VARCHAR(150) NULL,
    VALOR_ANTERIOR TEXT NULL,
    VALOR_NUEVO TEXT NULL,
    VALORES_ANTERIORES_JSON TEXT NULL,
    VALORES_NUEVOS_JSON TEXT NULL,
    ID_USUARIO BIGINT NULL,
    CORREO_USUARIO VARCHAR(150) NULL,
    NOMBRE_USUARIO VARCHAR(200) NULL,
    ENDPOINT VARCHAR(250) NULL,
    METODO_HTTP VARCHAR(20) NULL,
    MODULO VARCHAR(100) NULL,
    IP_ORIGEN VARCHAR(100) NULL,
    USER_AGENT VARCHAR(500) NULL,
    FECHA_EVENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OBSERVACION VARCHAR(500) NULL
);

CREATE INDEX IDX_LOG_AUDITORIA_TABLA_REGISTRO ON LOG_AUDITORIA (NOMBRE_TABLA, ID_REGISTRO);
CREATE INDEX IDX_LOG_AUDITORIA_USUARIO ON LOG_AUDITORIA (ID_USUARIO);
CREATE INDEX IDX_LOG_AUDITORIA_FECHA ON LOG_AUDITORIA (FECHA_EVENTO);
CREATE INDEX IDX_LOG_AUDITORIA_ACCION ON LOG_AUDITORIA (ACCION);
CREATE INDEX IDX_LOG_AUDITORIA_MODULO ON LOG_AUDITORIA (MODULO);
